apiVersion: apps/v1
kind: Deployment
metadata:
    name: openliberty-12factor-app-b-deployment
spec:
    selector:
        matchLabels:
            app: 12factor-app-b
    replicas: 2
    template:
        metadata:
            labels:
                app: 12factor-app-b
        spec:
            containers:
                - name: 12factor-app-b
                  image: openliberty-12factor-app-b:1.0-SNAPSHOT
                  ports:
                      - containerPort: 9081
                      - containerPort: 9443
                  env:
                      - name: lifetime
                        value: "0"
                      - name: failFrequency
                        value: "4"

